build:
  maxIssues: 0

complexity:
  ComplexInterface:
    active: true
  LabeledExpression:
    active: true
  MethodOverloading:
    active: true
  StringLiteralDuplication:
    active: true

exceptions:
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

formatting:
  autoCorrect: false
  MaximumLineLength:
    maxLineLength: 140

performance:
  active: true
  ArrayPrimitive:
    active: true
  SpreadOperator:
    active: false

potential-bugs:
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  DataClassShouldBeImmutable:
    active: true
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenVoid:
    active: true
  FunctionOnlyReturningConstant:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
  MagicNumber:
    active: false # Noisy, catches things like Duration.ofHours(24), etc.
  MandatoryBracesIfStatements:
    active: true
  MaxLineLength:
    maxLineLength: 140
  MayBeConst:
    active: true
  NoTabs:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    max: 4
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseRequire:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: true
    excludes: ''
    excludeImports: ''
